name:                cellular-automata
version:             0.1.0.0
gitlab:              "hu-hbo-ict/ai/cellular-automata"
license:             BSD3
author:              "Brian van der Bijl"
maintainer:          "brian.vanderbijl@hu.nl"
copyright:           "2020 Brian van der Bijl"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitLab at <https://gitlab.com/hu-hbo-ict/ai/v2dep-opdrachten/-/blob/main/1_cellular-automata/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cellular-automata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cellular-automata
