name:                recursie-lijsten
version:             0.1.0.0
gitlab:              "hu-hbo-ict/ai/recursie-lijsten"
license:             BSD3
author:              "Brian van der Bijl"
maintainer:          "brian.vanderbijl@hu.nl"
copyright:           "2020 Brian van der Bijl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://gitlab.com/hu-hbo-ict/ai/recursie-lijsten#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  recursie-lijsten-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recursie-lijsten
